[project]
name = "gestures"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adb-shell>=0.4.4",
    "mediapipe>=0.10.32",
    "opencv-contrib-python>=4.13.0.92",
    "pyautogui>=0.9.54",
]
